### ISSUE TITLE
Blender 4.0 Compatibility Issues

### ISSUE THREAD

**Issue by ghost** [DrachenSeele/SuperImageDenoiser#22] opened 2023-11-16 05:37 UTC
**Describe the bug**
SID refuses to work with B4 Stable.

**To Reproduce**
1. Click Render Tab
2. Click on the Create SID Denoiser button

**Expected behavior**
A denoising node setup should show in the compositor.

**Screenshots**

**System Information (please complete the following information):**
 - OS: Windows 11
 - Blender Version: 4.00 Stable
 - Addon Version: 4.0 Latest Gumroad release

**Additional context**

**Comment by DrachenSeele** [comment] 2023-11-16 06:21
Closed because duplicate of [ Issue #19](https://github.com/PidgeonTools/SuperImageDenoiser/issues/19)

**Closed as completed by DrachenSeele** 2023-11-16 06:21 UTC
Labels: bug
