### ISSUE TITLE
Denoiser Error

### ISSUE THREAD

**Issue by DER01** [DrachenSeele/SuperImageDenoiser#27] opened 2024-09-13 16:32 UTC
**Describe the bug**

**To Reproduce**
1. Go to 'Add Super Denoiser'
2. Click on 'Add Super Denoiser'
3. When clicking on 'Add SID', the error message appears. 
4.
![SID Error 2024-09-13](https://github.com/user-attachments/assets/9f99c58d-502f-4df2-9b16-a82ab94b1568)

**Expected behavior**
That SID would open

**Screenshots**

**System Information (please complete the following information):**
 - OS: Windows
 - Blender Version: 4.2
 - Addon Version: 4.0

**Additional context**

**Comment by DrachenSeele** [comment] 2024-09-13 16:46
Closed because duplicate of [Issue #19](https://github.com/PidgeonTools/SuperImageDenoiser/issues/19)

**Closed as completed** 2024-09-13 16:47 UTC
Labels: bug
