### ISSUE TITLE
Unable to add SID

### ISSUE THREAD

**Issue by BaoZhengchen** [DrachenSeele/SuperImageDenoiser#23] opened 2023-11-17 07:15 UTC
![image](https://github.com/PidgeonTools/SuperImageDenoiser/assets/105910999/2d2f1f76-3d25-4d93-a01a-e104ae73069c)
Python: Traceback (most recent call last):
  File "C:\Users\25693\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\SuperImageDenoiser-master\SuperImageDenoiser.py", line 83, in execute
    sid_standard_tree = create_sid_denoiser_standard()
  File "C:\Users\25693\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\SuperImageDenoiser-master\SID_QualityStandart.py", line 16, in create_sid_denoiser_standard
    sid_tree.inputs.new("NodeSocketColor", "Noisy Image")
AttributeError: 'CompositorNodeTree' object has no attribute 'inputs'

**Comment by codybaraks** [comment] 2023-11-17 07:17
Python: Traceback (most recent call last):
  File "C:\Users\Earvin\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\SuperImageDenoiser\SuperImageDenoiser.py", line 83, in execute
    sid_standard_tree = create_sid_denoiser_standard()
  File "C:\Users\Earvin\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\SuperImageDenoiser\SID_QualityStandart.py", line 16, in create_sid_denoiser_standard
    sid_tree.inputs.new("NodeSocketColor", "Noisy Image")
AttributeError: 'CompositorNodeTree' object has no attribute 'inputs'

**Comment by DrachenSeele** [comment] 2023-11-17 07:33
Duplicate of [issue #19](https://github.com/PidgeonTools/SuperImageDenoiser/issues/19)

**Closed as completed by DrachenSeele** 2023-11-17 07:33 UTC
Labels: bug

**Comment by codybaraks** [comment] 2023-11-17 07:40
Thanks!
