### ISSUE TITLE
Hope for the support for the 4.0 version

### ISSUE THREAD

**Issue by rpgmylife** [DrachenSeele/SuperImageDenoiser#20] opened 2023-11-15 15:25 UTC
**Is your feature request related to a problem? Please describe.**
I tried the latest SID, hit "Add Super Denoiser" button, and below is the error info:
Python: Traceback (most recent call last):
  File "C:\Users\rpgyo\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\SuperImageDenoiser\SuperImageDenoiser.py", line 83, in execute
    sid_standard_tree = create_sid_denoiser_standard()
  File "C:\Users\rpgyo\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\SuperImageDenoiser\SID_QualityStandart.py", line 16, in create_sid_denoiser_standard
    sid_tree.inputs.new("NodeSocketColor", "Noisy Image")
AttributeError: 'CompositorNodeTree' object has no attribute 'inputs'
 

**Describe the solution you'd like**
I really love SID and I will wait for the support of the blender 4.0

**Describe alternatives you've considered**
I may try to save the SID node group as a present.

**Additional context**
<img width="683" alt="image" src="https://github.com/PidgeonTools/SuperImageDenoiser/assets/60959587/6673de7c-8981-488e-8843-8e7cd8fdcdf0">

**Comment by DrachenSeele** [comment] 2023-11-15 15:55
Closed because duplicate of [Issue #19](https://github.com/PidgeonTools/SuperImageDenoiser/issues/19)

**Closed as completed by DrachenSeele** 2023-11-15 15:55 UTC
Labels: enhancement
