### ISSUE TITLE
SID crashes when pressing Add/Refresh Super Denoiser

### ISSUE THREAD

**Issue by thebattybat** [DrachenSeele/SuperImageDenoiser#25] opened 2024-01-16 00:47 UTC
**Describe the bug**
When I click "Add Super Denoiser" or "Refresh Super Denoiser" It removes my Composite node in the Compositing tab and then shows a whole bunch of errors. 

**To Reproduce**
1. Go to the Render Properties tab.
2. Remove standard denoising on the render.
3. Set render samples lower (I use 50 in viewport and 140 for render)
4. Scroll down to and then click on Create Super Denoiser.
5. Click on ''Add Super Denoiser'' or ''Refresh Super Denoiser''
6. See error

**Expected behavior**
I think that it should have added the Super Denoiser to my scene/compositing/renders.

**Screenshots**
![Screenshot 2024-01-15 192543](https://github.com/PidgeonTools/SuperImageDenoiser/assets/111093647/e1510a2d-cff3-4dbe-adc9-e99e4ec93e59)

**System Information (please complete the following information):**
 - OS: [Windows 11]
 - Blender Version: [Blender 4.0]
 - Addon Version: [4.0.0]

**Comment by DrachenSeele** [comment] 2024-01-16 06:05
Closed because duplicate of [Issue #19](https://github.com/PidgeonTools/SuperImageDenoiser/issues/19)

**Closed as completed by DrachenSeele** 2024-01-16 06:05 UTC
Labels: bug

**Comment by BlenderDefender** [comment] 2025-08-12 11:14
The referenced issue is pretty generic, so here's a bit of context:
The Blender API introduced breaking changes in Blender 4.0, and we've decided not to continue development on the standalone version of SID. We have fixed the issues with Blender 4.0 in our addon "Pidgeon Tool Bag" instead. You can get it on https://blendermarket.com/products/pidgeontoolbag

(For future reference)
