### ISSUE TITLE
Python: Traceback

### ISSUE THREAD

**Issue by ArtemPredator** [DrachenSeele/SuperImageDenoiser#24] opened 2023-12-13 17:02 UTC
Can't add SuperDenoiser node. Not sure it's my bug or update missed something.

1. Instaled SuperImageDenoiser-master to AppData
2. Clicked on "Add Super Denoiser" in Cycles Render settings
3. Getting Error

What can cause this problem?

![изображение_2023-12-13_195908722](https://github.com/PidgeonTools/SuperImageDenoiser/assets/99890713/0c256253-0971-4392-8679-09b39fbc0563)

**System Information (please complete the following information):**
 - OS: Windows 10
 - Blender Version: 4.0
 - Addon Version: 4.0

**Comment by DrachenSeele** [comment] 2023-12-13 17:17
Closed because duplicate of [Issue #19](https://github.com/PidgeonTools/SuperImageDenoiser/issues/19)

**Closed as completed by DrachenSeele** 2023-12-13 17:17 UTC
Labels: bug
